name: Twenty Two Avenue API Deploy

on:
  push:
    branches:
      - master # Deploy when pushing to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 21098
          script: |
            cd api.ttavenue.com

            # Stash changes
            git stash

            # Pull the latest code
            git pull origin master

            # Install dependencies
            composer install
            composer dump-autoload

            php artisan migrate --force
